controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

csv_import:
    path: /csv/import
    controller: App\Controller\CsvImportController::importAction



